version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/back"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker-compose"
    directories:
      - "/"
      - "back"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "docker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"